spring.application.name=GymOn
spring.datasource.url=jdbc:postgresql://localhost:5432/jgym
spring.datasource.username=postgres
spring.datasource.password=elpsycongroo1
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true